version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Berlin"