stages:
  - test
  - deploy

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: ciphersuite
    POSTGRES_USER: django
    POSTGRES_PASSWORD: "start123"
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

staging:
  stage: deploy
  image: ubuntu:latest
  environment:
    name: Ciphersuite Devel
    url: https://ciphersuite-info.herokuapp.com
  before_script:
    - apt-get update -y && apt-get install -y ruby-dev curl gnupg2
    - gem install dpl
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=ciphersuite-info --api-key=$HEROKU_API_KEY
    - heroku run 'python manage.py compilescss && \
        python manage.py collectstatic && \
        python manage.py migrate && \
        python manage.py loaddata directory/fixtures/* && \
        python manage.py scrapeiana' \
        --app ciphersuite-info