stages:
  - test
  - deploy

services:
  - postgres:latest

variables:
  POSTGRES_DB: ciphersuite
  POSTGRES_USER: django
  POSTGRES_PASSWORD: "start123"

before_script:
  - pip install -r requirements.txt

test-job:
  stage: test
  script:
    - python manage.py test