stages:
  - test
  - deploy

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: ciphersuite
    POSTGRES_USER: django
    POSTGRES_PASSWORD: "start123"
  script:
    - python manage.py test

staging:
  stage: deploy
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: ciphersuite
    POSTGRES_USER: django
    POSTGRES_PASSWORD: "start123"
  environment:
    name: Ciphersuite Nightly
    url: https://csi-dev.hcrudolph.com
  script:
    - python manage.py compilescss
    - python manage.py migrate
    - python manage.py loaddata directory/fixtures/*
    - python manage.py scrapeiana
    - echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('$CSI_ADMIN', 'root@hcrudolph.com', '$CSI_ADMIN_PASS')" | python manage.py shell
    - gunicorn --bind=:8080 --daemon csinfo.wsgi
