image: python:3.6

stages:
  - test

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: ciphersuite
    POSTGRES_USER: django
    POSTGRES_PASSWORD: "start123"
  before_script:
    - pip install -r requirements/requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate --run-syncdb
    - python manage.py loaddata directory/fixtures/*
    - python manage.py scrapeiana
    - python manage.py filltlsversion
    - python manage.py updatesecurity
    - python manage.py collectstatic -c --noinput
  script:
    - python manage.py test