services:
  - postgres:latest

variables:
  POSTGRES_DB: ciphersuite
  POSTGRES_USER: django
  POSTGRES_PASSWORD: "start123"

before_script:
  - apk add \
    python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
  - pip install -r requirements.txt

test:
  - python manage.py test