stages:
  - test
  - deploy

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: ciphersuite
    POSTGRES_USER: django
    POSTGRES_PASSWORD: "start123"
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test

staging:
  stage: deploy
  image: ruby:latest
  environment:
    name: Ciphersuite Devel
    url: https://ciphersuite-info.herokuapp.com
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=ciphersuite-info --api-key=$HEROKU_API_KEY \
      --run 'python manage.py compilescss' \
      --run 'python manage.py collectstatic' \
      --run 'python manage.py migrate' \
      --run 'python manage.py loaddata directory/fixtures/*' \
      --run 'python manage.py scrapeiana'