stages:
  - build
  - test
  - deploy

services:
  - postgres:latest

variables:
  POSTGRES_DB: ciphersuite
  POSTGRES_USER: django
  POSTGRES_PASSWORD: "start123"

before_script:
  - apk add python3

job 1:
  stage: build
  script: pip install -r requirements.txt


job 2:
  stage: test
  script: python manage.py test